import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Saad",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike fit pant",
      category: "Pants",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas fit Pant",
      category: "Pants",
      image: "/images/p2.jpg",
      price: 130,
      countInStock: 15,
      brand: "Adidas",
      rating: 3.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "Puma fit Pant",
      category: "Pant",
      image: "/images/p3.jpg",
      price: 120,
      countInStock: 20,
      brand: "Puma",
      rating: 4.5,
      numReviews: 12,
      description: "high quality product",
    },
    {
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 99,
      countInStock: 0,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Lacoste Slim Shirt",
      category: "Shirts",
      image: "/images/p5.jpg",
      price: 120,
      countInStock: 1,
      brand: "Lacoste",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Walmart Slim Shirt",
      category: "Shirts",
      image: "/images/p6.jpg",
      price: 120,
      countInStock: 12,
      brand: "Walmart",
      rating: 5,
      numReviews: 20,
      description: "high quality product",
    },
  ],
};
export default data;
